remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title: Sofien Dhouib
logo: id.jpg
description: sofiane.lastname@gmail.com
